---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-externaldns
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-contour
  interval: 1m0s
  path: ./external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
    namespace: tanzu-continuousdelivery-resources


