apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tmm-wordpress
  namespace: tanzu-helm-resources
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      version: '>15.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-helm-resources
      interval: 1m
  values:
    replicaCount: 1
    wordpressUsername: admin
    wordpressPassword: "SecurePass1!"
    mariadb.auth.rootPassword: "SecurePass1!"
