apiVersion: v1
data:
  default: gp2
  managed-premium: gp2
kind: ConfigMap
metadata:
  labels:
    velero.io/change-storage-class: RestoreItemAction
    velero.io/plugin-config: ""
  name: change-storage-class-config
  namespace: velero