---
grafana:
  service:
    type: ClusterIP
  secret:
    type: "Opaque"
    admin_password: "Vk13YXJlMSE="
  pvc:
    storageClassName:
ingress:
  enabled: true
  virtual_host_fqdn: "dashboard.tanzu.eks.spuchol.me"
  prefix: "/"
  servicePort: 80

