---
grafana:
  service:
    type: ClusterIP
  secret:
    type: "Opaque"
    admin_password: "Vk13YXJlMSE="
  pvc:
    storageClassName:
ingress:
  enabled: true
  virtual_host_fqdn: "dashboard.operations.cpod-v8u1tanzu.az-fkd.cloud-garage.net"
  prefix: "/"
  servicePort: 80