---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: externaldns-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: externaldns-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: externaldns-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: externaldns-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: externaldns
  namespace: packages
spec:
  serviceAccountName: externaldns-packages-sa
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 0.12.2+vmware.4-tkg.2
  values:
  - secretRef:
      name: externaldns-packages-values